### ISSUE TITLE
Error on optional loops

### ISSUE THREAD

**Issue by arkanovicz** [kevinpt/syntrax#6]
On the following spec file:

    opt(loop('A',None))

syntrax 1.0 throws:

    Rendering to test.png using cairo backend
    Traceback (most recent call last):
      File "/usr/local/bin/syntrax", line 11, in <module>
        load_entry_point('syntrax==1.0', 'console_scripts', 'syntrax')()
      File "/usr/local/lib/python2.7/dist-packages/syntrax.py", line 2028, in main
        render_railroad(spec, args.title, url_map, args.output, backend, styles, args.scale, args.transparent)
      File "/usr/local/lib/python2.7/dist-packages/syntrax.py", line 1747, in render_railroad
        layout.draw_diagram(spec)
      File "/usr/local/lib/python2.7/dist-packages/syntrax.py", line 1678, in draw_diagram
        return self.draw_line(spec[1:])
      File "/usr/local/lib/python2.7/dist-packages/syntrax.py", line 1287, in draw_line
        t, texx, texy = self.draw_diagram(term) # Draw each element
      File "/usr/local/lib/python2.7/dist-packages/syntrax.py", line 1695, in draw_diagram
        return self.draw_or([None, args])
      File "/usr/local/lib/python2.7/dist-packages/syntrax.py", line 1604, in draw_or
        m[i] = mx = self.draw_diagram(term)
      File "/usr/local/lib/python2.7/dist-packages/syntrax.py", line 1673, in draw_diagram
        return self.draw_bubble(spec[0])
      File "/usr/local/lib/python2.7/dist-packages/syntrax.py", line 1206, in draw_bubble
        txt, node_style = self.format_text(txt)
      File "/usr/local/lib/python2.7/dist-packages/syntrax.py", line 1182, in format_text
        if re.match(ns.pattern, txt):
      File "/usr/lib/python2.7/re.py", line 141, in match
        return _compile(pattern, flags).match(string)
    TypeError: expected string or buffer

**Comment by inponomarev** [comment]
It seems that this project is dead. 

You may try [jsyntrax](https://github.com/atp-mipt/jsyntrax/) instead: this is a fresh reimplementation of `syntrax` in Java. 

jsyntrax 1.1 is free from this bug.
