### ISSUE TITLE
Add cairo as a dependency

### ISSUE THREAD

**Issue by multimeric** [kevinpt/syntrax#7]
It seems that `cairo` is a hard, non-conditional dependency:
https://github.com/kevinpt/syntrax/blob/eecc2714731ec6475d264326441e0f2a47467c28/syntrax.py#L16

However, it's not listed as a dependency: https://github.com/kevinpt/syntrax/blob/eecc2714731ec6475d264326441e0f2a47467c28/setup.py#L33

Thus, simply installing and then importing `syntrax` gives me:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tmp.GgRTr2Nt4J/venv/lib/python3.6/site-packages/syntrax.py", line 16, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
```

**Comment by multimeric** [comment]
Oh, and the same goes for `gi`. Even though I have pango and cairo installed on my (Linux) machine, I had to `pip install pycairo PyGObject` for it to work in a virtualenv. I recommend adding those both as dependencies for this package. I know of another package that uses cairo that does the same.
